### ISSUE TITLE
航行UI - 词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#14]
1. 技能栏翻页的Prev和Next中，Next未替换（注：0.951里prev和next都没翻译）
![UI](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/3d59a4ab-6aef-4095-9636-0eb7530c8f39)

2.舰队装甲状态
![UI2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/eed8622d-a5c8-4918-8aa7-86d6ac066f1d)

**Comment by jnxyp** [comment]
2 确认已解决
1 属于特殊词条，将会手工处理

**Comment by jnxyp** [comment]
确认已解决
