### ISSUE TITLE
星图UI - 部分说明文本未翻译

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#15]
### 1. 说明文本
1. 星景
![1](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/c70121ea-4e0d-41fc-b7ef-70ba03071d5f)

2. 续航距离 
![2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/cdfcc571-c4b7-431b-a05f-3e93b2292cae)

### 2. 个别词条
超空间
![3](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/ee191fd4-f14e-4a5d-bdbd-ab442e3980cd)

**Comment by ck1521** [comment]
补充：
遭受超空间风暴时的词条也未翻译
![2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/1d73743a-ae7e-409e-b5ce-7c481b7b4363)

**Comment by jnxyp** [comment]
确认已解决
