### ISSUE TITLE
舰船选择UI - 选中的词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#16]
1. 选择旗舰
![6](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/ee5e511d-dcc3-4930-aba9-1c13a118a27e)

2. 战斗部署
![5](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/f1759770-22df-4fc2-84e1-3c420d5f7c8f)

3. 修理遗弃船
![4](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/269c0a49-3dc4-4a05-a3f4-05efb252eac0)

**Comment by jnxyp** [comment]
确认已解决
