### ISSUE TITLE
特殊物品价格显示缺乏高亮（以及可能的格式问题）

### ISSUE THREAD

**Issue by osotoaoro** [TruthOriginem/Starsector-Localization-CN#29]
![N5@29401D{FQ7G~5{(7{0_O](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/c37a3ec5-8541-4f11-9986-eb0fb902b888)
![{N{74@D7NWP1{W TF(F$9NO](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/56ffea5e-c5e2-40de-ae0c-0ff1c71f5825)
作为参考：
![}6$P{)DPDV@MHYX$F$L8_CU](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/c9319961-16b5-4259-8e8d-ae6237917279)

**Comment by jnxyp** [comment]
已确认修复
