### ISSUE TITLE
确认类对话框内容未翻译

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#33]
1. 购买舰船
![1](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/3c43069e-53a2-471f-8745-be59eec24b01)

2. 修复D插舰船
![5](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/be90beb5-2c91-4d9f-a4e1-7d35e370177f)

3. 出售舰船
![2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/ea95733f-7671-4df6-af0e-a1c67a2cabd8)

**Comment by jnxyp** [comment]
确认已解决
