### ISSUE TITLE
舰船装配UI - 部分内容未翻译

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#34]
1. 船插UI词条（船插内容也有一些未汉化的，这个回头再单独列吧）
![9](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/0547a61b-8251-4de0-accb-9bcc56324571)

2. 特殊提示 - 装配方案不带武器时
![3](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/995368e5-7c91-42ed-81d4-a2c22bb2d413)

**Comment by jnxyp** [comment]
已确认修复
