### ISSUE TITLE
地图生成 - 天体名称词条未汉化

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#35]
### 1. Galatia星系
这个星系的词条可能和外面的不通用，以下几个天体词条在其他星系都是正常的，但是这个星系内还是英文词条

**星系内跳跃点**
![10](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/80aa022e-19da-417f-9f41-724e592a3ea4)

**边缘跳跃点**
![11](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/6ff57917-3eaa-4539-a50d-e187b66619cb)

**通信中继站**
![13](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/0db30ad4-c36f-46bd-b0b8-bde0715e78b6)

**采矿站**
![14](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/9e03176e-0250-4c31-9f5e-87d579ee4ea3)

**学院**
![12](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/dee5aed7-d6d4-46e0-95c2-b4acc8531a61)

**Comment by ck1521** [comment]
### 2. 疑似通用天体名

**行星磁场**
![112](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/287cc33e-56f9-4945-b5e9-1de7f872209c)

**Comment by ck1521** [comment]
### 3.疑似专用天体名

因为感觉词条会很零散，建议低优先级处理？

**1. 陨石带**
![111](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/4b0564a0-6091-465f-a054-759c6072927b)

**2. 陨石带**
![113](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/09d9f202-975b-4fb6-8238-736333647a41)

**3. 陨石带**
![114](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/e38937dc-c7be-410e-92ed-88154ae2af1f)

**4. 行星磁场，但是有名字（？）**
![115](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/fba9d694-fcda-473c-852b-9e147690995e)

**5.陨石带**
![116](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/d75a19fb-01ba-4ec2-89e4-0b8e4121010c)

**6.陨石带**
![117](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/80fa4c99-711c-48fc-971b-423c8edb0e61)

**7. 恒星的小行星带（游戏里的通用词条是行星环）**
![118](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/671ea76f-1126-4173-98fb-83a9cb4b3e03)

**Comment by jnxyp** [comment]
确认已解决
