### ISSUE TITLE
惡性bug : a != java.lang.String 導致遊戲崩潰

### ISSUE THREAD

**Issue by a9615161** [TruthOriginem/Starsector-Localization-CN#44]
最近新開的存檔時常跳出此警告後崩潰。
以下提供log的相關片段作為參考，看起來是翻譯的時候把source code相關的東西搞砸了
[稍微看了一下，好像都是在生成路德左徑艦隊之後產生的崩潰。]
`8773493 [Thread-9] INFO  sound.OooO  - Playing music with id [miscallenous_corvus_campaign_music.ogg]
8774167 [Thread-3] INFO  com.fs.starfarer.api.impl.campaign.fleets.BaseLimitedFleetManager  - Spawned fleet [?德左? 守?者] at hyperloc Vector2f[-15492.772, -2472.0562]
8775582 [Thread-3] INFO  com.fs.starfarer.api.impl.campaign.intel.AnalyzeEntityMissionIntel  - Created AnalyzeEntityMissionIntel: 人之?-探?器, ?力：非?力?体
8777866 [Thread-7] INFO  sound.O  - Cleaning up music with id [miscallenous_corvus_campaign_music.ogg]
8777995 [Thread-9] INFO  sound.O  - Creating streaming player for music with id [miscallenous_corvus_campaign_music.ogg]
8777995 [Thread-9] INFO  sound.OooO  - Playing music with id [miscallenous_corvus_campaign_music.ogg]
8778016 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.util.IllegalFormatConversionException: a != java.lang.String
java.util.IllegalFormatConversionException: a != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
	at java.util.Formatter$FormatSpecifier.printFloat(Unknown Source)
	at java.util.Formatter$FormatSpecifier.print(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)`
	
`842901 [Thread-3] INFO  com.fs.starfarer.api.impl.campaign.intel.AnalyzeEntityMissionIntel  - Created AnalyzeEntityMissionIntel: 人之?-探?器, ?力：霸主
843415 [Thread-3] INFO  com.fs.starfarer.api.impl.campaign.fleets.BaseLimitedFleetManager  - Spawned fleet [?德左? 守?者] at hyperloc Vector2f[-11495.639, -178.36928]
867208 [Thread-3] INFO  sound.O  - Cleaning up music with id [miscallenous_corvus_campaign_music.ogg]
867222 [Thread-7] INFO  sound.O  - Cleaning up music with id [campaign_music_part_2_v28.ogg]
867358 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.util.IllegalFormatConversionException: a != java.lang.String
java.util.IllegalFormatConversionException: a != java.lang.String`

**Comment by a9615161** [comment]
[mylog.zip](https://github.com/user-attachments/files/17157632/mylog.zip)
附上log檔案

**Comment by 53ndC0r30n1y** [comment]
我也遇到了

**Comment by jnxyp** [comment]
请尝试使用最新汉化文件

**Comment by jnxyp** [comment]
由于近期未复现，暂时关闭问题。
如有遇到可再次打开
