### ISSUE TITLE
战斗HUD - 未部署船时的提示语为???

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#46]
如图：
![1](https://github.com/user-attachments/assets/da6def02-d4b3-47d3-9057-2d6c544f8c14)

英文版词条：
![2](https://github.com/user-attachments/assets/82e32bff-8e1c-4e28-8e8b-c7f0c2b26baf)

（貌似是点阵字体问题）

**Comment by jnxyp** [comment]
已确认修复
