### ISSUE TITLE
地点情报（Jangala的卢德圣地） - 词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#49]
如图：
![4](https://github.com/user-attachments/assets/0066c46d-034c-41e6-bf8e-ff47d1a70448)
![5](https://github.com/user-attachments/assets/42bdfb5f-d26a-4c40-89b7-ebbfa43a3913)

（图中的Luddic Shrine - Jangala和Not Visited）

出现位置：Ancrya的新手教程结束后，第一次进Jangala酒吧

**Comment by ck1521** [comment]
![4](https://github.com/user-attachments/assets/84360c45-0910-42d9-ac48-1e7fb4a84582)
补充：访问后的Visited也是未替换词条

**Comment by jnxyp** [comment]
已添加词条，等待翻译
