### ISSUE TITLE
情报UI - stability词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#50]
如图：
![4](https://github.com/user-attachments/assets/9380fc9d-4941-4f99-85c6-6635debc5385)

（其他UI这个词条为“稳定性”）
还没看到海盗Raid，不确定是只有Pather还是都没替换

**Comment by ck1521** [comment]
海盗Raid没问题，只有Pather这个事件的词条有问题

**Comment by jnxyp** [comment]
已添加，等待翻译
