### ISSUE TITLE
情报UI - 超空间测绘部分词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#52]
探索任务 - 超空间测绘的1，2，4，6阶段，对应的名称词条未替换
如图：
![4](https://github.com/user-attachments/assets/028ac158-0cf9-4bce-b829-7656f0ccf65c)
![5](https://github.com/user-attachments/assets/d9d3613c-96bc-44bc-8f3b-147df1e4b62d)
![6](https://github.com/user-attachments/assets/fff2b839-e2d9-49d8-a8fa-8f23d55e4afe)
![7](https://github.com/user-attachments/assets/04d11ae5-9259-45ee-8d1a-6e369511489a)

**Comment by jnxyp** [comment]
已添加，等待翻译
