### ISSUE TITLE
星图UI - Yesod跳跃点词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#53]
如图：
![4](https://github.com/user-attachments/assets/00d5de75-71a3-42d1-afb0-647355634e25)

另外随便看了几处其他核心星系的跳跃点词条（包括以星域，星球，或者独立命名的）都是正常的
可能Yesod这里是个单独的词条漏掉了

**Comment by jnxyp** [comment]
已修复
