### ISSUE TITLE
大地图 - 个别天体词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#54]
如图：
![3](https://github.com/user-attachments/assets/7c220277-d925-4369-872d-af102ebdd31b)

（Asteroid Belt）

看了下核心星系大部分背景天体的词条都是对的
小行星带这个可能是个别遗漏

**Comment by jnxyp** [comment]
请问这个是在哪个星系？

另外请确认没有使用任何Mod（包括前置），因为有些前置mod可能会修改部分名称

**Comment by jnxyp** [comment]
检查了一下，这些小行星带和磁场都是随机生成的，名字是从物体名称随机池里取的。

翻译了一些具有明确含义的名字，例如 Asteroid Belt 小行星带 和 Magnet Field 磁场
也翻译了一些词语中可以意译的部分，例如 Ring of XXX XXX 之环
其它这些无法意译的按惯例不进行翻译
