### ISSUE TITLE
角色技能 - 部分文本未高亮显示

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-Localization-CN#7]
示例如图：
![2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/43a00aaa-f8a4-4686-8161-6325bd1bbf24)

对比 0.951汉化版的效果：
![1](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/f0c80e4f-9b55-4813-8611-43b8a8b5a309)

**Comment by ck1521** [comment]
对比了一下0.951，在 影响 这一栏中，除存在 “xx与oo” 这种情况以外，其他情况下词条均为**全文高亮** 
"xx与oo"的情况是xx和oo高亮

**Comment by jnxyp** [comment]
确认已解决
